"""
Auth exceptions
"""

# from core.exceptions.base import CustomException
